### PR TITLE
Use npm scripts instead of grunt

### PR DESCRIPTION
**Pull request by joanniclaborde**
This is a duplicate of #6... It was merged into master too early, so I forced push a revert to master, and not GitHub is all mixed up. So let's use this PR now.

### CODE REVIEW

**Comment by joanniclaborde** [comment]
One last thing we forgot to consider: when creating a new site from scratch, with `vagrant site create`, the plugin gets the latest site template with `git clone https://github.com/solidusjs/solidus-site-template.git`. This means that when we'll release the new template, the users of the old plugin will not be able to create new sites anymore (unless they specify the template to use as a command line option).

One thing we could do is match the solidus-site-template to clone with the current vagrant-solidus version. For example if the current vagrant-solidus version is `2.1.1`, it will checkout the `solidus-site-template#2` branch. Many branches would then be available in that repo, and could live in parallel.

Or, we version the whole repo as a node module or a ruby gem, and use npm or gem to install the right version.

@josiahsprague @pushred any better idea?

**Comment by pushred** [comment]
That's fine, the only users we have for this thing are going to be pushed to upgrade when all the site PRs are merged. Can't we just use Git tags to version the template and specify a tag somewhere in the plugin config?

**Comment by joanniclaborde** [comment]
Duh, yeah tags are much simpler than branches, they can be moved around easily in case we need to find bugs, etc. I'll do that, thanks!

**Comment by joanniclaborde** [comment]
Done, with last commit. Don't forget to release the template changes, tag them, then update the tag here before merging this PR.

**Comment by pushred** [comment]
Let's go ahead and release this today so UX can get up and running with the migration sites. If they need to work with any other sites before we get Josiah's updates out the door they can update the package config.

**Pull request merged**
